In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [ ]:
X_train

    age  gender  fever   cough       city
77    8  Female  101.0    Mild    Kolkata
82   24    Male   98.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
91   38    Male    NaN    Mild      Delhi
67   65    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
83   17  Female  104.0    Mild    Kolkata
22   71  Female   98.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
9    64  Female  101.0    Mild      Delhi
27   33  Female  102.0  Strong      Delhi

[80 rows x 5 columns]

In [ ]:
si = SimpleImputer() # by default strategy = mean
X_train_fever=si.fit_transform(X_train[['fever']])

X_test_fever=si.fit_transform(X_test[['fever']])
print(X_train_fever.shape)

(80, 1)

In [ ]:
# OrdinalEnCoding -> cough
oe= OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])

X_test_cough=oe.fit_transform(X_test[['cough']])
print(X_train_cough.shape)

(80, 1)

In [ ]:
# OneHotEncoding -> gender, city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

X_train_gender_city.shape ,type(X_train_gender_city)

((80, 4), numpy.ndarray)

In [ ]:
# Extracting Age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape , type(X_train_age)

((80, 1), numpy.ndarray)

In [ ]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed , X_test_transformed

(array([[  8.       , 101.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 24.       ,  98.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 51.       , 101.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 38.       , 100.8630137,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 65.       ,  99.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 14.       ,  99.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 26.       ,  98.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 49.       ,  99.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 72.       ,  99.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 70.       , 103.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 83.       , 101.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 80.       ,  98.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 31.       ,  98.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 11.       , 100.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 34.       , 101.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [ 64.       ,  98.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 38.       , 101.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 51.       , 104.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 83.       , 103.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 75.       , 104.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [ 47.       , 100.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 19.       , 100.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 65.       ,  98.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 25.       ,  99.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 13.       , 100.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 23.       , 100.8630137,   1.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 34.       ,  98.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 19.       , 101.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 73.       ,  98.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 16.       , 103.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 65.       , 101.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 27.       , 100.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 68.       , 101.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [ 42.       , 101.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 49.       , 101.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 46.       , 103.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [  5.       , 102.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 60.       ,  99.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 12.       , 104.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 74.       , 102.       ,   1.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 65.       ,  99.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 59.       ,  99.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [ 75.       , 100.8630137,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 64.       , 102.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 11.       , 100.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [  6.       , 104.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 20.       , 102.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [ 82.       , 100.8630137,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 66.       ,  99.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 49.       , 102.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 81.       , 101.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 69.       , 102.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 55.       , 100.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 18.       , 104.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 16.       , 104.       ,   1.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 24.       , 102.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 42.       , 100.8630137,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 23.       ,  98.       ,   1.       ,   0.       ,   0.       ,
           1.       ,   1.       ],
        [ 27.       , 100.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [  5.       , 100.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 82.       , 102.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 20.       , 100.8630137,   0.       ,   0.       ,   0.       ,
           1.       ,   1.       ],
        [ 48.       , 103.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 80.       , 100.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 51.       , 104.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 34.       , 104.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ],
        [  5.       ,  98.       ,   0.       ,   0.       ,   0.       ,
           1.       ,   1.       ],
        [ 19.       , 100.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 15.       , 101.       ,   1.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 82.       , 102.       ,   0.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 73.       , 103.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 42.       , 104.       ,   1.       ,   0.       ,   0.       ,
           1.       ,   0.       ],
        [ 14.       , 101.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 25.       , 104.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 12.       ,  98.       ,   1.       ,   0.       ,   0.       ,
           0.       ,   1.       ],
        [ 17.       , 104.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   0.       ],
        [ 71.       ,  98.       ,   0.       ,   0.       ,   1.       ,
           0.       ,   1.       ],
        [ 84.       , 100.8630137,   0.       ,   0.       ,   0.       ,
           0.       ,   0.       ],
        [ 64.       , 101.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   0.       ],
        [ 33.       , 102.       ,   0.       ,   1.       ,   0.       ,
           0.       ,   1.       ]]),
 array([[ 83.        ,  98.        ,   1.        ,   1.        ,
           0.        ,   0.        ,   0.        ],
        [ 81.        ,  98.        ,   0.        ,   0.        ,
           0.        ,   1.        ,   1.        ],
        [ 27.        , 100.        ,   1.        ,   0.        ,
           1.        ,   0.        ,   0.        ],
        [ 20.        , 101.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ],
        [ 22.        ,  99.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ],
        [ 69.        , 103.        ,   0.        ,   0.        ,
           1.        ,   0.        ,   0.        ],
        [ 54.        , 104.        ,   0.        ,   0.        ,
           1.        ,   0.        ,   1.        ],
        [ 19.        , 101.        ,   1.        ,   1.        ,
           0.        ,   0.        ,   0.        ],
        [ 47.        , 101.        ,   1.        ,   0.        ,
           0.        ,   0.        ,   1.        ],
        [ 69.        ,  98.        ,   0.        ,   0.        ,
           0.        ,   1.        ,   1.        ],
        [ 60.        , 103.        ,   1.        ,   0.        ,
           1.        ,   0.        ,   0.        ],
        [ 71.        , 100.76470588,   1.        ,   0.        ,
           1.        ,   0.        ,   1.        ],
        [ 10.        , 100.        ,   1.        ,   0.        ,
           0.        ,   0.        ,   0.        ],
        [ 79.        , 100.76470588,   1.        ,   0.        ,
           1.        ,   0.        ,   1.        ],
        [ 56.        , 104.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   1.        ],
        [ 34.        , 100.76470588,   0.        ,   0.        ,
           0.        ,   1.        ,   1.        ],
        [ 44.        , 104.        ,   1.        ,   0.        ,
           0.        ,   1.        ,   0.        ],
        [ 40.        ,  98.        ,   0.        ,   1.        ,
           0.        ,   0.        ,   1.        ],
        [ 10.        ,  98.        ,   0.        ,   0.        ,
           1.        ,   0.        ,   1.        ],
        [ 50.        , 103.        ,   0.        ,   0.        ,
           1.        ,   0.        ,   0.        ]]))

In [ ]:
X_train_transformed.shape , X_test_transformed.shape

((80, 7), (20, 7))

# **Simplify**

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer=ColumnTransformer(transformers=[
('tnf1',SimpleImputer(),['fever']),('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                             ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])],remainder='passthrough')

In [ ]:
transformer.fit_transform(X_train)

array([[101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   8.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [101.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [100.8630137,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  38.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  65.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  26.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  49.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  72.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  70.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [ 98.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  80.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  31.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  11.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  38.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  19.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  13.       ],
       [100.8630137,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  34.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  19.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  73.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  16.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  68.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  46.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  60.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  74.       ],
       [ 99.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  65.       ],
       [ 99.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  59.       ],
       [100.8630137,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  11.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   6.       ],
       [102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [100.8630137,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [ 99.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  66.       ],
       [102.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [102.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  69.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  55.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  18.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  16.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  24.       ],
       [100.8630137,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  42.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [100.8630137,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  20.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  48.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  80.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  51.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   5.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  19.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  15.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  82.       ],
       [103.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  73.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  42.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  14.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  25.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  17.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [100.8630137,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  84.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  64.       ],
       [102.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  33.       ]])

In [ ]:
transformer.transform(X_test).shape

(20, 7)

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
!git clone https://github.com/Sanket71/Machine-Learning.git

Cloning into 'Machine-Learning'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 40 (delta 10), reused 25 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (40/40), 410.35 KiB | 4.19 MiB/s, done.
Resolving deltas: 100% (10/10), done.

In [14]:
%cd Machine-Learning

/content/Machine-Learning/Machine-Learning

In [4]:
!mkdir -p Column-Transformer

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/column-transformer.ipynb" Column-Transformer/

In [9]:
!git add .

In [6]:
!git config --global user.email "sanketmeshiya8933@gmail.com"
!git config --global user.name "Sanket71"

In [7]:
from getpass import getpass
token = getpass('Enter GitHub token: ')

Enter GitHub token: ··········

In [10]:
!git commit -m "Add column-Transformer notebook"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [11]:
!git remote set-url origin https://{token}@github.com/Sanket71/Machine-Learning.git
!git push origin main --force

Everything up-to-date